services:
  # Database Service
  db:
    image: postgres:16-alpine
    container_name: ctf_postgres
    restart: always
    environment:
      POSTGRES_USER: ctf_user
      POSTGRES_PASSWORD: ctf_password
      POSTGRES_DB: ctf_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Database GUI
  # Access at http://localhost:5051
  pgadmin:
    image: dpage/pgadmin4
    container_name: ctf_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db

volumes:
  postgres_data:
